export enum PayoutCategory {
  GAS_BILL = 'GAS_BILL',
  ELECTRICITY = 'ELECTRICITY',
  WIFI_BILL = 'WIFI_BILL',
  HOME_RENT = 'HOME_RENT',
  MAID_BILL = 'MAID_BILL',
  MEMBER_REFUND = 'MEMBER_REFUND',
  OTHER = 'OTHER',
}
